#!/bin/bash
set -e

source common.sh

while test "$1"; do
  case "$1" in
    -*) die "$1 is not an option";;
    *) arg="$1";shift
      test "$LOCAL" || { LOCAL="$arg";continue; }
      ;;
  esac
done

set -x

LOCAL="${LOCAL-.}"
mkdir -p "$LOCAL"

(cd "$LOCAL"
  export GIT_WORK_TREE="$PWD"
  export GIT_DIR="$GIT_WORK_TREE/.gito"
  git init --share=group --template="$SCRIPT_DIR/template"
  initrepo "$PWD"
  git add .
  git commit --allow-empty -m "Gito auto inito" || true
)
