#!/bin/bash
set -e

source common.sh

connect() {
  setrepo "$1"
  git remote add origin "$2/.gito" \
    || git remote set-url origin "$2/.gito" \
    || true
  git push -u origin master &>/dev/null || true
}

REMOTE="${1}"
LOCAL="${2-.}"

if [ "$REMOTE" ]; then
  REMOTE_FILE="${REMOTE#*:}"
  grep -q : <<<"$REMOTE" && ssh_mode="ssh ${REMOTE%%:*} -- . ~/.profile \\\\;"

  $ssh_mode test -d "$REMOTE_FILE" || remote_empty=1
  [[ -d "$LOCAL" && "`find "$LOCAL"/* -maxdepth 0`" ]] || local_empty=1

  if [[ "$local_empty" && "$remote_empty" ]]; then
    $ssh_mode gito init "$REMOTE_FILE"
    gito clone "$REMOTE" "$LOCAL"
  elif [[ ! "$local_empty" && "$remote_empty" ]]; then
    $ssh_mode gito init --no-commit "$REMOTE_FILE"
    gito init "$LOCAL"
    connect "$LOCAL" "$REMOTE"
  elif [[ "$local_empty" && ! "$remote_empty" ]]; then
    $ssh_mode gito init "$REMOTE_FILE"
    gito clone "$REMOTE" "$LOCAL"
  elif [[ ! "$local_empty" && ! "$remote_empty" ]]; then
    $ssh_mode gito init --no-commit "$REMOTE_FILE"
    gito init "$LOCAL"
    connect "$LOCAL" "$REMOTE"
  fi
fi

gito listen "$LOCAL"
